version: '2'
services:
  # these services are totally micro
  counter:
    build: ./counter-app
    links:
      - store:r0.dat
  motd:
    build: ./motd-app
    links:
      - store:r0.dat

  # NoSQL for you
  store:
    image: redis
    volumes_from:
      - store_config
  store_config:
    build: ./redis-config

  # Web scale
  balancer:
    image: nginx
    ports:
      - 80:80
    links:
      - counter:c01.srv
      - motd:m01.srv
    volumes_from:
      - balancer_config
  balancer_config:
    build: ./nginx-config
